<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-FUG8PLT" ignored="0" name="Test" tests="5" failures="1" timestamp="2020-09-11T02:06:22 IST" time="781.967" errors="0">
  <testcase name="feature" time="100.608" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="80.309" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="401.775" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="140.058" classname="cucumber.api.testng.AbstractTestNGCucumberTests"/>
  <testcase name="feature" time="57.732" classname="cucumber.api.testng.AbstractTestNGCucumberTests">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [08/09/2020] but found [09-08-2020]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [08/09/2020] but found [09-08-2020]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at java.util.ArrayList.forEach(Unknown Source)
Caused by: java.lang.AssertionError: expected [08/09/2020] but found [09-08-2020]
at com.onlineDashboardApplication.stepDefination.TestPeopleFocusDashboard.check_same_set_of_data_should_be_displayed_in_the_people_focus_table(TestPeopleFocusDashboard.java:78)
at âœ½.Then Checks Same set of data should be displayed in the people focus table(05_PeopleFocusDashboard.feature:10)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite> <!-- Test -->
